// <auto-generated />
using LearningProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LearningProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200223175745_ChangedVkPublicsClass")]
    partial class ChangedVkPublicsClass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LearningProject.Models.VkPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int>("VkPublicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VkPublicId");

                    b.ToTable("VkPosts");
                });

            modelBuilder.Entity("LearningProject.Models.VkPublic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Descritption")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("IsAdvertiser")
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photo100")
                        .HasColumnType("text");

                    b.Property<string>("Photo200")
                        .HasColumnType("text");

                    b.Property<string>("Photo50")
                        .HasColumnType("text");

                    b.Property<string>("ScreenName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("VkId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VkPublics");
                });

            modelBuilder.Entity("LearningProject.Models.VkPost", b =>
                {
                    b.HasOne("LearningProject.Models.VkPublic", "VkPublic")
                        .WithMany("Posts")
                        .HasForeignKey("VkPublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
