# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PyTesseract.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PyTesseract.proto',
  package='PyTesseract',
  syntax='proto3',
  serialized_options=b'\252\002\025PyTesseract.Generated',
  serialized_pb=b'\n\x11PyTesseract.proto\x12\x0bPyTesseract\"%\n\x11ParseImageRequest\x12\x10\n\x08ImageUri\x18\x01 \x01(\t\"\x1f\n\x0fParseImageReply\x12\x0c\n\x04Text\x18\x01 \x01(\t2Y\n\x0bPyTesseract\x12J\n\nParseImage\x12\x1e.PyTesseract.ParseImageRequest\x1a\x1c.PyTesseract.ParseImageReplyB\x18\xaa\x02\x15PyTesseract.Generatedb\x06proto3'
)




_PARSEIMAGEREQUEST = _descriptor.Descriptor(
  name='ParseImageRequest',
  full_name='PyTesseract.ParseImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ImageUri', full_name='PyTesseract.ParseImageRequest.ImageUri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)


_PARSEIMAGEREPLY = _descriptor.Descriptor(
  name='ParseImageReply',
  full_name='PyTesseract.ParseImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Text', full_name='PyTesseract.ParseImageReply.Text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['ParseImageRequest'] = _PARSEIMAGEREQUEST
DESCRIPTOR.message_types_by_name['ParseImageReply'] = _PARSEIMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParseImageRequest = _reflection.GeneratedProtocolMessageType('ParseImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _PARSEIMAGEREQUEST,
  '__module__' : 'PyTesseract_pb2'
  # @@protoc_insertion_point(class_scope:PyTesseract.ParseImageRequest)
  })
_sym_db.RegisterMessage(ParseImageRequest)

ParseImageReply = _reflection.GeneratedProtocolMessageType('ParseImageReply', (_message.Message,), {
  'DESCRIPTOR' : _PARSEIMAGEREPLY,
  '__module__' : 'PyTesseract_pb2'
  # @@protoc_insertion_point(class_scope:PyTesseract.ParseImageReply)
  })
_sym_db.RegisterMessage(ParseImageReply)


DESCRIPTOR._options = None

_PYTESSERACT = _descriptor.ServiceDescriptor(
  name='PyTesseract',
  full_name='PyTesseract.PyTesseract',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='ParseImage',
    full_name='PyTesseract.PyTesseract.ParseImage',
    index=0,
    containing_service=None,
    input_type=_PARSEIMAGEREQUEST,
    output_type=_PARSEIMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYTESSERACT)

DESCRIPTOR.services_by_name['PyTesseract'] = _PYTESSERACT

# @@protoc_insertion_point(module_scope)
