# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import PyTesseract_pb2 as PyTesseract__pb2


class PyTesseractStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseImage = channel.unary_unary(
                '/PyTesseract.PyTesseract/ParseImage',
                request_serializer=PyTesseract__pb2.ParseImageRequest.SerializeToString,
                response_deserializer=PyTesseract__pb2.ParseImageReply.FromString,
                )


class PyTesseractServicer(object):
    """Missing associated documentation comment in .proto file"""

    def ParseImage(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PyTesseractServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseImage,
                    request_deserializer=PyTesseract__pb2.ParseImageRequest.FromString,
                    response_serializer=PyTesseract__pb2.ParseImageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PyTesseract.PyTesseract', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PyTesseract(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def ParseImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyTesseract.PyTesseract/ParseImage',
            PyTesseract__pb2.ParseImageRequest.SerializeToString,
            PyTesseract__pb2.ParseImageReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
